<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\BlockGame.PluginApi\BlockGame.PluginApi.csproj" Private="false" />
    <ProjectReference Include="..\BlockGame.PluginApi.Minigames\BlockGame.PluginApi.Minigames.csproj" />
    <None Include="plugin.yml" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
